sudo: false
language: scala
scala:
  - 2.12.1
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
addons:
  mariadb: "10.0"
  postgresql: "9.3"
before_script:
  - mkdir -p $HOME/.sbt/launchers/0.13.8/
  - curl -L -o $HOME/.sbt/launchers/0.13.8/sbt-launch.jar http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar
  - mysql -e 'create database tablespec;'
  - mysql -e 'create database cross_reference;'
  - mysql -e 'create database special_types;'
  - psql -c 'create database tablespec owner travis;' -U postgres
  - psql -c 'create database cross_reference owner travis;' -U postgres
  - psql -c 'create database special_types owner travis;' -U postgres
